### ISSUE TITLE
Add Ionic Support

### ISSUE THREAD

**Issue by Barlocker-Garrett** [WebsiteBeaver/CordovaCall#34]
- Hide webView when receiveCall, sendCall, connectedCall are used to show the CallKit native UI

Adding `[self.webView setBackgroundColor:[UIColor clearColor]];` to receiveCall works, but not for the others.

**Comment by D-Marc1** [comment]
Sorry, I'm not really sure what you're asking for. What does Ionic Framework have anything to do with this plugin?

**Comment by mhartington** [comment]
Hi there, Ionic dev here.

Ionic doesn't do anything differently than any other UI kit (Framework7, Onsen, etc).
Though in my test, while the plugin calls are successful, the native UI is hidden behind the web view.

**Comment by mhartington** [comment]
Hm, I never considered the WKWebview plugin 🤔 
I'll see if I cant take a look and try to send along a PR

**Comment by dmarcs** [comment]
I might be misunderstanding the problem, but it seems to be working as expected. In order to test this out, I created an ionic project and called `receiveCall` as shown below. This is exactly what happens with Cordova. The incoming call screen displays, and once you accept the call the native call UI goes behind your app. That's also what happens if you use CallKit natively. It's just how CallKit works. There might be a hacky way to bring the call UI back to the front, but I wouldn't recommend doing that. The best thing to do is to create your own buttons (hangup, mute, reverse camera) in your app. You can add an `onClick` event for your hangup button that calls this plugin's `endCall` function for example.

![ionic-callkit](https://user-images.githubusercontent.com/26162804/38778431-9f2acd66-4087-11e8-8e0f-75a167593e38.gif)
