### ISSUE TITLE
VoIP app is missing from stock Contacts app on iOS

### ISSUE THREAD

**Issue by rmanasyan** [WebsiteBeaver/CordovaCall#39]
Hi,

looks like this plugin should support this feature when voip app can be opened (called via) from ios contacts but it does not work for me...

please see how WhatsApp is added to the list on this screenshot as example
![img_0432](https://user-images.githubusercontent.com/1284773/39933582-1751cd3e-554c-11e8-86da-b1bbd7c70f4d.png)

is this something that can be done by updating supportedHandleTypes with CXHandleTypePhoneNumber or I'm just missing some configuration to make it work?

thank you!

**Comment by rmanasyan** [comment]
it's not exactly about making a call from Recents, the scenario is: 
open Phone book on iOS, select any contact, get my voip app listed in the action sheet along with WhatsApp and other callkit enabled apps

can you please confirm if this feature is supported in this plugin?

thank you

ps: setIncludeInRecents(true) is set

**Comment by dmarcs** [comment]
Good catch! You're right about using `CXHandleTypePhoneNumber`. I changed `CXHandleTypeGeneric` to `CXHandleTypePhoneNumber`, and now CordovaCall supports calling from contacts in addition to recents. You can either tap and hold the phone or video, and it will force open your app and call the person using your VOIP app. I'm sure you already made the changes to your app, but we appreciate you raising the issue because it will help other app developers in the future.


![cordovacall](https://user-images.githubusercontent.com/26162804/40286483-3b65bd54-5c75-11e8-81a3-17211b806aa1.gif)

**Comment by rmanasyan** [comment]
thanks! it works now with version 1.1.5
