### ISSUE TITLE
"Choose SIM for this call" Dialog when placing regular calls

### ISSUE THREAD

**Issue by rcidt** [WebsiteBeaver/CordovaCall#43]
Hey guys thanks for the awesome work! 

On android, every time I try and make a call from the native contacts or recents, I see a dialog which asks me to "Choose SIM for this call", with 2 options: make a call with my carrier SIM, or with my calling cordova app.

On some devices I've tested there is no option to choose a default, so this is triggered on every single call, which makes this issue a blocker for us.

Is there a way to get around this?

Thanks!

**Comment by sachingarg05** [comment]
Did you find anything realted to this? Our app can only receive calls, not make outgoing calls. So this popup showing app's name everytime user tries to make a call from standard dialer app is only going to confuse users.

**Comment by rcidt** [comment]
@sachingarg05 nope, I did not find a solution. It is not WebsiteBeaver's fault though... it's just a very poor android API. I have no clue why android would make a half-baked api make it into production. It is truly unusable.

**Comment by dmarcs** [comment]
@rcidt I agree that Android should improve this. Unfortunately I haven't found a way around it yet. For me calls get stored in recents as `Unknown`. We considered getting around this by storing contacts in the user's phonebook, but decided against it because you have to ask for permission to write into the user's phonebook. It doesn't seem right to modify someone's phonebook. Please let me know if you think of a solution to this problem. If there isn't one now, I'm sure Android will release a way to fix this in the future. This isn't a problem with Apple CallKit. You can call from recents without any problems. At least you're able to initiate a call from recents using Android, but unfortunately it sounds like there's no way around the dialog.
