### ISSUE TITLE
Android Studio compatible code

### ISSUE THREAD

**Issue by omkarnathsingh** [WebsiteBeaver/CordovaCall#45]
How can I use this code in Android Studio 3? I don't see proper code for it. Guide me please. Thanks in advance.

**Comment by D-Marc1** [comment]
I have no idea what you're asking. This is a Cordova plugin, knowledge of Cordova is a must obviously.

**Comment by SkyzohKey** [comment]
I'm currently porting this for react-native stay tuned ;)

**Comment by dmarcs** [comment]
@omkarnathsingh Check out https://cordova.apache.org/docs/en/latest/guide/cli/index.html. It shows how to install and get a Cordova project running. Once you add this plugin and add Android to your project, you'll be able to open the code in Android Studio. Let me know if you need help with that. If you don't want to use Cordova, you can find the Java code here: https://github.com/WebsiteBeaver/CordovaCall/tree/master/src/android, but you'll have to modify it slightly because it's setup for Cordova.
